### ISSUE TITLE
A way to enable `includeStacktraces` in `LineFormatter`

### ISSUE THREAD

**Issue by zerkms** [symfony/MonologBundle#136]
Am I missing something or there is no way to enable this flag through the configuration?

https://github.com/Seldaek/monolog/blob/master/src/Monolog/Formatter/LineFormatter.php#L47

If that's right - what is the recommended way to enable it? May be we might have an option for that?

**Comment by Seldaek** [comment]
We don't really support configuration of formatters at all right now. You can define your own service though and then use it in the handler using `formatter: service_id`, and you can in the service definition use `methods: { includeStacktraces: [true] }` IIRC to set that up correctly.

**Comment by zerkms** [comment]
Okay, sounds reasonable, thanks.

Do you think it must be kept opened then? I think no.

**Comment by Seldaek** [comment]
No I guess not..
