### ISSUE TITLE
Update to the last change on monolog

### ISSUE THREAD

**Issue by Garfield-fr** [symfony/MonologBundle#17]
Important change is the date and time on log file

https://github.com/Seldaek/monolog/pull/94

Thanks

Bertrand

**Comment by Incher25** [comment]
How can I fix the timezone properly? In vendor/monolog/monolog/src/Monolog/Logger.php default timezone defined as 
`if (!static::$timezone) {
            static::$timezone = new \DateTimeZone(date_default_timezone_get() ?: 'UTC');
        }`
so I sould add date_default_timezone_set('My timezone'), for example, in AppKernel.php, but what if I want just use timezone setting from my php.ini?

**Comment by Seldaek** [comment]
@Incher25 date_default_timezone_get() returns what is defined in php.ini as date.timezone, so if you set that monolog will use it.
