### ISSUE TITLE
Add anti-404 activation strategy service/class

### ISSUE THREAD

**Issue by Seldaek** [symfony/MonologBundle#5]
A simple class that avoids triggering the FingersCrossedHandler on 404 errors would be nice. It should still trigger on other 4xx though. This should be made optional I suppose, unless everyone agrees it's a better default. /cc @stof @schmittjoh @fabpot

**Comment by jmauerhan** [comment]
Is there a way to make it just exclude all 404s, not just for a specific url? I can't get this to work.

**Comment by Seldaek** [comment]
Excluding this works for me `- ^/`

**Comment by jmauerhan** [comment]
I tried that, and it didn't work, so must have been something else wrong. I thought that would do it so I just wanted to check. Thanks :)
