### ISSUE TITLE
Exclude 403 (4XX) Errors from the Log 

### ISSUE THREAD

**Issue by lyrixx** [symfony/MonologBundle#89]
Hello.

If I throw a `Symfony\Component\Security\Core\Exception\AccessDeniedException`
or a `Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException` I do not want a log about this exception, because I thrown it.

For the security, The `Symfony\Component\Security\Core\Exception\AccessDeniedException` is converted to a `Symfony\Component\HttpKernel\Exception\AccessDeniedHttpException` in the `Symfony\Component\Security\Http\Firewall\ExceptionListener::handleAccessDeniedException`.

I think we can extends the configuration to all kind of exception in the namespace `Symfony\Component\HttpKernel\Exception\*`, because If **I** throw an HttpKernel exception, it don't want a log.

What do you think ?

**Comment by dkarlovi** [comment]
I feel you shouldn't have closed this. Things like [Sentry](https://getsentry.com/welcome/) are becoming more common place and we should be able to tweak the output, there's no reason not to do it.

**Comment by Seldaek** [comment]
@dkarlovi I don't see how this related to tweaking output format to sentry..

**Comment by dkarlovi** [comment]
@Seldaek sorry, I was unclear: I meant "output" as in "output to the underlying logging target", not related to formatting in any way.

In our case, we track a Symfony app (Sylius, to be more exact) which generates roughly 2,5k 404 events daily, most of which are from random bots and stuff we cannot control. The 404 itself is logged to Google Analytics so it will not go unnoticed, but it's not really an error (we the devs can do anything about). So we mute them in Sentry, but it still needs to process them for no reason.

It would be great to be able to filter events by status code or instance type, for example. I feel it's very similar to already existing `NotFoundActivationStrategy`, but more flexible and better matching common uses cases.

**Comment by Seldaek** [comment]
Yeah, I agree it might be nice to have more advanced config format (although doing it yourself in code is really not hard..), as I wrote in https://github.com/symfony/monolog-bundle/issues/89#issuecomment-57245247 PRs are welcome :)

You can still use excluded_404s to easily filter the 404 which is IMO the main problem. The rest if your API returns a lot of 400 or something then you can build your own activation strategy or PR something, but I am not going to spend time on it, and I don't think it's important enough to warrant having an open issue, that's why I closed it.

**Comment by fmonts** [comment]
I'm trying to do the same (do not log 4xx errors) but I see some ERRORS which should be critical and I don't want to miss, like this one for example (it couldn't connect to the smtp server due to a firewall rule, and all the outgoing mail went lost):

> app.ERROR: Exception occurred while flushing email queue: Connection could not be established with host 10.2.78.219 [Connection timed out #110] [] []

so I don't think excluding ERROR level logs is a good idea...

**Comment by wodka** [comment]
a simple solution is to add a custom activation strategy:

```yaml
monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
            activation_strategy: my.activation.strategy # service id
```

and then have a service like the following:
```php
<?php

use Monolog\Handler\FingersCrossed\ErrorLevelActivationStrategy;
use Symfony\Component\HttpKernel\Exception\HttpException;
use JMS\DiExtraBundle\Annotation as DI;

/**
 * Activation strategy for logs
 *
 * @DI\Service("my.activation.strategy")
 */
class LogActivationStrategy extends ErrorLevelActivationStrategy
{
    /**
     * LogActivationStrategy constructor.
     */
    public function __construct()
    {
        parent::__construct('error');
    }

    /**
     * @param array $record
     *
     * @return bool
     */
    public function isHandlerActivated(array $record)
    {
        $isActivated = parent::isHandlerActivated($record);
        if (
            $isActivated
            && isset($record['context']['exception'])
        ) {
            $exception = $record['context']['exception'];

            if ($exception instanceof HttpException) {
                // only log exceptions outside of 404 and 403
                return !in_array($exception->getStatusCode(), [403, 404]);
            }
        }

        return $isActivated;
    }
}
```

**Comment by gitnik** [comment]
It seems that this only works `fingers crossed` type. Doesn't seem to work for a `stream`

**Comment by RichardBradley** [comment]
You can achieve this by replacing the default `twig.exception_listener` service with one that has your own implementation of `logException`, i.e.

    # in services.yml:
    twig.exception_listener:
        class: AppBundle\Logging\MyExceptionListener
        arguments:
            - "%twig.exception_listener.controller%"
            - "@logger"
        tags:
            - { name: kernel.event_subscriber }
            - { name: monolog.logger, channel: request }

    # MyExceptionListener.php
    <?php
    
    namespace AppBundle\Logging;
    
    use Symfony\Component\HttpKernel\EventListener\ExceptionListener;
    use Symfony\Component\HttpKernel\Exception\HttpExceptionInterface;
    
    class MyExceptionListener extends ExceptionListener {
    
        /**
         * Override to turn down the log level on expected HTTP errors like
         * Not Found.
         */
        protected function logException(\Exception $exception, $message) {
            if (null !== $this->logger) {
                if ($exception instanceof HttpExceptionInterface
                    && $exception->getStatusCode() == 404) {
    
                    // Log at WARN level, which will still appear, but skip the
                    // exception, as the stack trace will not be interesting but
                    // will be large
                    $this->logger->warning($message);
                } else {
                    parent::logException($exception, $message);
                }
            }
        }
    }

A doc page about this would probably help.

In fact, a doc page about how to override the standard services with your own ones would be helpful. I had to grep `vendor` to find `twig.xml` to implement this, and it doesn't look particularly stable against changes to twig's default settings.

**Comment by dkarlovi** [comment]
@RichardBradley you can also [decorate the service](http://symfony.com/doc/current/service_container/service_decoration.html) instead of replacing it, this should be somewhat more stable.

**Comment by RichardBradley** [comment]
@dkarlovi, although that sounds like it would help, it doesn't really solve any of the fragility I'm worried about here :-(

Currently, if the constructor arguments or anything else of note in the ExceptionListener implementation changes in the next version of Symfony, then my replacement service will break.

If I were to try to use a service decorator instead of replacing the service, I would still need to inherit from `ExceptionListener` in order to override the `logException` method. So I would still need to hardcode the matching constructor arguments and would still be exposed to the same risks re future changes.

A decorator version might look like:

```
# in services.yml:
my_exception_listener:
    class: AppBundle\Logging\MyExceptionListener
    decorates: twig.exception_listener
    arguments:  # (can't pull these out of "inner" service, as they're protected)
        - "%twig.exception_listener.controller%"
        - "@logger"
    # "tags" may or may not still be needed?

# MyExceptionListener.php
<?php

namespace AppBundle\Logging;

use Symfony\Component\HttpKernel\EventListener\ExceptionListener;
use Symfony\Component\HttpKernel\Exception\HttpExceptionInterface;

class MyExceptionListener extends ExceptionListener {

    /**
     * Override to turn down the log level on expected HTTP errors like
     * Not Found.
     */
    protected function logException(\Exception $exception, $message) {
        if (null !== $this->logger) {
            if ($exception instanceof HttpExceptionInterface
                && $exception->getStatusCode() == 404) {

                // Log at WARN level, which will still appear, but skip the
                // exception, as the stack trace will not be interesting but
                // will be large
                $this->logger->warning($message);
            } else {
                parent::logException($exception, $message);
            }
        }
    }
}
```

**Comment by lukepass** [comment]
Any news about this issue? I would like to be able to filter Monolog exceptions based on their HTTP status code or their exception code.

Is it possible?

Thanks.

**Comment by mikemix** [comment]
@lukepass there's already [a solution](https://github.com/symfony/monolog-bundle/issues/89#issuecomment-267575337) in this thread.

**Comment by ToBe998** [comment]
Sadly above solution is only for fingers_crossed as shown above and way to complex compared to a simple config entry for the handler. Yes it might work in some cases, but it's ver impractical.

So we fall back to creating our own handlers for sentry :(

**Comment by fmonts** [comment]
It is now possible in Symfony 4.1 https://symfony.com/blog/new-in-symfony-4-1-ignore-specific-http-codes-from-logs

**Comment by lukepass** [comment]
Thanks fmonts! Would it be possible to backport this to 3.4 using a bundle?

**Comment by Richard87** [comment]
Hi!

I have added `excluded_http_codes: [403, 404]` to all my logg-handlers, but I still receive *alot* of access-denied emails after ugprading from 4.0.8 to 4.1.0:

https://paste.gnome.org/panmtutis#line-37
https://i.imgur.com/s2X5mNb.png

**Comment by phillipsnick** [comment]
Would be amazing to see this in 3.4, currently have to create services for each of my handlers and filter out there.
